server.port=8086
spring.main.web-application-type=reactive

###############################################
# ADMIN REQUESTS (REST)
###############################################
spring.cloud.gateway.routes[0].id=admin-requests
spring.cloud.gateway.routes[0].uri=http://administrativerequests:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/requests/**

###############################################
# PUBLIC SERVICES (GraphQL)
###############################################
spring.cloud.gateway.routes[1].id=public-services
spring.cloud.gateway.routes[1].uri=http://publicservices:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/graphql

###############################################
# CIVIL REGISTRY (SOAP)
###############################################
spring.cloud.gateway.routes[2].id=civil-registry
spring.cloud.gateway.routes[2].uri=http://civilregistry:8089
spring.cloud.gateway.routes[2].predicates[0]=Path=/CivilRegistry
