// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface GetPositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.GetPositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool inQueue = 1;</code>
   * @return The inQueue.
   */
  boolean getInQueue();

  /**
   * <code>int32 position = 2;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <code>int32 waiting = 3;</code>
   * @return The waiting.
   */
  int getWaiting();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
