// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface JoinQueueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.JoinQueueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceId = 1;</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <code>string serviceId = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>string locationId = 2;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string locationId = 2;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <pre>
   * optional client metadata (phone, channel...) could be added
   * </pre>
   *
   * <code>string userId = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * optional client metadata (phone, channel...) could be added
   * </pre>
   *
   * <code>string userId = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
