// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface QueueStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.QueueStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceId = 1;</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <code>string serviceId = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();

  /**
   * <code>string locationId = 2;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string locationId = 2;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <pre>
   * optional: userId to receive targeted messages
   * </pre>
   *
   * <code>string userId = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * optional: userId to receive targeted messages
   * </pre>
   *
   * <code>string userId = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
