// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface QueueStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.QueueStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * user this update is about (empty if general)
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * user this update is about (empty if general)
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 1-based position
   * </pre>
   *
   * <code>int32 position = 2;</code>
   * @return The position.
   */
  int getPosition();

  /**
   * <pre>
   * total waiting
   * </pre>
   *
   * <code>int32 waiting = 3;</code>
   * @return The waiting.
   */
  int getWaiting();

  /**
   * <pre>
   * "joined", "left", "served", "position_changed", "stats"
   * </pre>
   *
   * <code>string event = 4;</code>
   * @return The event.
   */
  java.lang.String getEvent();
  /**
   * <pre>
   * "joined", "left", "served", "position_changed", "stats"
   * </pre>
   *
   * <code>string event = 4;</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();

  /**
   * <pre>
   * optional textual detail
   * </pre>
   *
   * <code>string detail = 5;</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <pre>
   * optional textual detail
   * </pre>
   *
   * <code>string detail = 5;</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();

  /**
   * <pre>
   * timestamp ISO8601
   * </pre>
   *
   * <code>string updatedAt = 6;</code>
   * @return The updatedAt.
   */
  java.lang.String getUpdatedAt();
  /**
   * <pre>
   * timestamp ISO8601
   * </pre>
   *
   * <code>string updatedAt = 6;</code>
   * @return The bytes for updatedAt.
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();
}
