// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

/**
 * Protobuf type {@code queue.QueueStatusResponse}
 */
public  final class QueueStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:queue.QueueStatusResponse)
    QueueStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueueStatusResponse.newBuilder() to construct.
  private QueueStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueueStatusResponse() {
    userId_ = "";
    event_ = "";
    detail_ = "";
    updatedAt_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueueStatusResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueueStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 16: {

            position_ = input.readInt32();
            break;
          }
          case 24: {

            waiting_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            event_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            detail_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            updatedAt_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.QueueAndUpdateService.grpc.QueueProto.internal_static_queue_QueueStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.QueueAndUpdateService.grpc.QueueProto.internal_static_queue_QueueStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.QueueAndUpdateService.grpc.QueueStatusResponse.class, com.example.QueueAndUpdateService.grpc.QueueStatusResponse.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   * user this update is about (empty if general)
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * user this update is about (empty if general)
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private int position_;
  /**
   * <pre>
   * 1-based position
   * </pre>
   *
   * <code>int32 position = 2;</code>
   * @return The position.
   */
  public int getPosition() {
    return position_;
  }

  public static final int WAITING_FIELD_NUMBER = 3;
  private int waiting_;
  /**
   * <pre>
   * total waiting
   * </pre>
   *
   * <code>int32 waiting = 3;</code>
   * @return The waiting.
   */
  public int getWaiting() {
    return waiting_;
  }

  public static final int EVENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object event_;
  /**
   * <pre>
   * "joined", "left", "served", "position_changed", "stats"
   * </pre>
   *
   * <code>string event = 4;</code>
   * @return The event.
   */
  public java.lang.String getEvent() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      event_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "joined", "left", "served", "position_changed", "stats"
   * </pre>
   *
   * <code>string event = 4;</code>
   * @return The bytes for event.
   */
  public com.google.protobuf.ByteString
      getEventBytes() {
    java.lang.Object ref = event_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      event_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAIL_FIELD_NUMBER = 5;
  private volatile java.lang.Object detail_;
  /**
   * <pre>
   * optional textual detail
   * </pre>
   *
   * <code>string detail = 5;</code>
   * @return The detail.
   */
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      detail_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional textual detail
   * </pre>
   *
   * <code>string detail = 5;</code>
   * @return The bytes for detail.
   */
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEDAT_FIELD_NUMBER = 6;
  private volatile java.lang.Object updatedAt_;
  /**
   * <pre>
   * timestamp ISO8601
   * </pre>
   *
   * <code>string updatedAt = 6;</code>
   * @return The updatedAt.
   */
  public java.lang.String getUpdatedAt() {
    java.lang.Object ref = updatedAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedAt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * timestamp ISO8601
   * </pre>
   *
   * <code>string updatedAt = 6;</code>
   * @return The bytes for updatedAt.
   */
  public com.google.protobuf.ByteString
      getUpdatedAtBytes() {
    java.lang.Object ref = updatedAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (position_ != 0) {
      output.writeInt32(2, position_);
    }
    if (waiting_ != 0) {
      output.writeInt32(3, waiting_);
    }
    if (!getEventBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, event_);
    }
    if (!getDetailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, detail_);
    }
    if (!getUpdatedAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, updatedAt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (position_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, position_);
    }
    if (waiting_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, waiting_);
    }
    if (!getEventBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, event_);
    }
    if (!getDetailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, detail_);
    }
    if (!getUpdatedAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, updatedAt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.QueueAndUpdateService.grpc.QueueStatusResponse)) {
      return super.equals(obj);
    }
    com.example.QueueAndUpdateService.grpc.QueueStatusResponse other = (com.example.QueueAndUpdateService.grpc.QueueStatusResponse) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (getPosition()
        != other.getPosition()) return false;
    if (getWaiting()
        != other.getWaiting()) return false;
    if (!getEvent()
        .equals(other.getEvent())) return false;
    if (!getDetail()
        .equals(other.getDetail())) return false;
    if (!getUpdatedAt()
        .equals(other.getUpdatedAt())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition();
    hash = (37 * hash) + WAITING_FIELD_NUMBER;
    hash = (53 * hash) + getWaiting();
    hash = (37 * hash) + EVENT_FIELD_NUMBER;
    hash = (53 * hash) + getEvent().hashCode();
    hash = (37 * hash) + DETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getDetail().hashCode();
    hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedAt().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.QueueAndUpdateService.grpc.QueueStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code queue.QueueStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:queue.QueueStatusResponse)
      com.example.QueueAndUpdateService.grpc.QueueStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.QueueAndUpdateService.grpc.QueueProto.internal_static_queue_QueueStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.QueueAndUpdateService.grpc.QueueProto.internal_static_queue_QueueStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.QueueAndUpdateService.grpc.QueueStatusResponse.class, com.example.QueueAndUpdateService.grpc.QueueStatusResponse.Builder.class);
    }

    // Construct using com.example.QueueAndUpdateService.grpc.QueueStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      position_ = 0;

      waiting_ = 0;

      event_ = "";

      detail_ = "";

      updatedAt_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.QueueAndUpdateService.grpc.QueueProto.internal_static_queue_QueueStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.example.QueueAndUpdateService.grpc.QueueStatusResponse getDefaultInstanceForType() {
      return com.example.QueueAndUpdateService.grpc.QueueStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.QueueAndUpdateService.grpc.QueueStatusResponse build() {
      com.example.QueueAndUpdateService.grpc.QueueStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.QueueAndUpdateService.grpc.QueueStatusResponse buildPartial() {
      com.example.QueueAndUpdateService.grpc.QueueStatusResponse result = new com.example.QueueAndUpdateService.grpc.QueueStatusResponse(this);
      result.userId_ = userId_;
      result.position_ = position_;
      result.waiting_ = waiting_;
      result.event_ = event_;
      result.detail_ = detail_;
      result.updatedAt_ = updatedAt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.QueueAndUpdateService.grpc.QueueStatusResponse) {
        return mergeFrom((com.example.QueueAndUpdateService.grpc.QueueStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.QueueAndUpdateService.grpc.QueueStatusResponse other) {
      if (other == com.example.QueueAndUpdateService.grpc.QueueStatusResponse.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (other.getPosition() != 0) {
        setPosition(other.getPosition());
      }
      if (other.getWaiting() != 0) {
        setWaiting(other.getWaiting());
      }
      if (!other.getEvent().isEmpty()) {
        event_ = other.event_;
        onChanged();
      }
      if (!other.getDetail().isEmpty()) {
        detail_ = other.detail_;
        onChanged();
      }
      if (!other.getUpdatedAt().isEmpty()) {
        updatedAt_ = other.updatedAt_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.QueueAndUpdateService.grpc.QueueStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.QueueAndUpdateService.grpc.QueueStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * user this update is about (empty if general)
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * user this update is about (empty if general)
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * user this update is about (empty if general)
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * user this update is about (empty if general)
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * user this update is about (empty if general)
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private int position_ ;
    /**
     * <pre>
     * 1-based position
     * </pre>
     *
     * <code>int32 position = 2;</code>
     * @return The position.
     */
    public int getPosition() {
      return position_;
    }
    /**
     * <pre>
     * 1-based position
     * </pre>
     *
     * <code>int32 position = 2;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(int value) {
      
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1-based position
     * </pre>
     *
     * <code>int32 position = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      
      position_ = 0;
      onChanged();
      return this;
    }

    private int waiting_ ;
    /**
     * <pre>
     * total waiting
     * </pre>
     *
     * <code>int32 waiting = 3;</code>
     * @return The waiting.
     */
    public int getWaiting() {
      return waiting_;
    }
    /**
     * <pre>
     * total waiting
     * </pre>
     *
     * <code>int32 waiting = 3;</code>
     * @param value The waiting to set.
     * @return This builder for chaining.
     */
    public Builder setWaiting(int value) {
      
      waiting_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total waiting
     * </pre>
     *
     * <code>int32 waiting = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWaiting() {
      
      waiting_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object event_ = "";
    /**
     * <pre>
     * "joined", "left", "served", "position_changed", "stats"
     * </pre>
     *
     * <code>string event = 4;</code>
     * @return The event.
     */
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "joined", "left", "served", "position_changed", "stats"
     * </pre>
     *
     * <code>string event = 4;</code>
     * @return The bytes for event.
     */
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "joined", "left", "served", "position_changed", "stats"
     * </pre>
     *
     * <code>string event = 4;</code>
     * @param value The event to set.
     * @return This builder for chaining.
     */
    public Builder setEvent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      event_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "joined", "left", "served", "position_changed", "stats"
     * </pre>
     *
     * <code>string event = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvent() {
      
      event_ = getDefaultInstance().getEvent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "joined", "left", "served", "position_changed", "stats"
     * </pre>
     *
     * <code>string event = 4;</code>
     * @param value The bytes for event to set.
     * @return This builder for chaining.
     */
    public Builder setEventBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      event_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <pre>
     * optional textual detail
     * </pre>
     *
     * <code>string detail = 5;</code>
     * @return The detail.
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional textual detail
     * </pre>
     *
     * <code>string detail = 5;</code>
     * @return The bytes for detail.
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional textual detail
     * </pre>
     *
     * <code>string detail = 5;</code>
     * @param value The detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      detail_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional textual detail
     * </pre>
     *
     * <code>string detail = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetail() {
      
      detail_ = getDefaultInstance().getDetail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional textual detail
     * </pre>
     *
     * <code>string detail = 5;</code>
     * @param value The bytes for detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      detail_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatedAt_ = "";
    /**
     * <pre>
     * timestamp ISO8601
     * </pre>
     *
     * <code>string updatedAt = 6;</code>
     * @return The updatedAt.
     */
    public java.lang.String getUpdatedAt() {
      java.lang.Object ref = updatedAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * timestamp ISO8601
     * </pre>
     *
     * <code>string updatedAt = 6;</code>
     * @return The bytes for updatedAt.
     */
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * timestamp ISO8601
     * </pre>
     *
     * <code>string updatedAt = 6;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * timestamp ISO8601
     * </pre>
     *
     * <code>string updatedAt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      
      updatedAt_ = getDefaultInstance().getUpdatedAt();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * timestamp ISO8601
     * </pre>
     *
     * <code>string updatedAt = 6;</code>
     * @param value The bytes for updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedAt_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:queue.QueueStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:queue.QueueStatusResponse)
  private static final com.example.QueueAndUpdateService.grpc.QueueStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.QueueAndUpdateService.grpc.QueueStatusResponse();
  }

  public static com.example.QueueAndUpdateService.grpc.QueueStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueueStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<QueueStatusResponse>() {
    @java.lang.Override
    public QueueStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueueStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueueStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueueStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.QueueAndUpdateService.grpc.QueueStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

