// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public final class QueueProto {
  private QueueProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_JoinQueueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_JoinQueueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_JoinQueueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_JoinQueueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_LeaveQueueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_LeaveQueueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_LeaveQueueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_LeaveQueueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_QueueStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_QueueStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_QueueStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_QueueStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_GetPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_GetPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_GetPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_GetPositionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013queue.proto\022\005queue\"I\n\020JoinQueueRequest" +
      "\022\021\n\tserviceId\030\001 \001(\t\022\022\n\nlocationId\030\002 \001(\t\022" +
      "\016\n\006userId\030\003 \001(\t\"X\n\021JoinQueueResponse\022\017\n\007" +
      "success\030\001 \001(\010\022\020\n\010position\030\002 \001(\005\022\017\n\007waiti" +
      "ng\030\003 \001(\005\022\017\n\007message\030\004 \001(\t\"J\n\021LeaveQueueR" +
      "equest\022\021\n\tserviceId\030\001 \001(\t\022\022\n\nlocationId\030" +
      "\002 \001(\t\022\016\n\006userId\030\003 \001(\t\"G\n\022LeaveQueueRespo" +
      "nse\022\017\n\007success\030\001 \001(\010\022\017\n\007waiting\030\002 \001(\005\022\017\n" +
      "\007message\030\003 \001(\t\"K\n\022QueueStatusRequest\022\021\n\t" +
      "serviceId\030\001 \001(\t\022\022\n\nlocationId\030\002 \001(\t\022\016\n\006u" +
      "serId\030\003 \001(\t\"z\n\023QueueStatusResponse\022\016\n\006us" +
      "erId\030\001 \001(\t\022\020\n\010position\030\002 \001(\005\022\017\n\007waiting\030" +
      "\003 \001(\005\022\r\n\005event\030\004 \001(\t\022\016\n\006detail\030\005 \001(\t\022\021\n\t" +
      "updatedAt\030\006 \001(\t\"K\n\022GetPositionRequest\022\021\n" +
      "\tserviceId\030\001 \001(\t\022\022\n\nlocationId\030\002 \001(\t\022\016\n\006" +
      "userId\030\003 \001(\t\"Z\n\023GetPositionResponse\022\017\n\007i" +
      "nQueue\030\001 \001(\010\022\020\n\010position\030\002 \001(\005\022\017\n\007waitin" +
      "g\030\003 \001(\005\022\017\n\007message\030\004 \001(\t2\245\002\n\014QueueServic" +
      "e\022>\n\tJoinQueue\022\027.queue.JoinQueueRequest\032" +
      "\030.queue.JoinQueueResponse\022A\n\nLeaveQueue\022" +
      "\030.queue.LeaveQueueRequest\032\031.queue.LeaveQ" +
      "ueueResponse\022L\n\021StreamQueueStatus\022\031.queu" +
      "e.QueueStatusRequest\032\032.queue.QueueStatus" +
      "Response0\001\022D\n\013GetPosition\022\031.queue.GetPos" +
      "itionRequest\032\032.queue.GetPositionResponse" +
      "B6\n&com.example.QueueAndUpdateService.gr" +
      "pcB\nQueueProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_queue_JoinQueueRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_queue_JoinQueueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_JoinQueueRequest_descriptor,
        new java.lang.String[] { "ServiceId", "LocationId", "UserId", });
    internal_static_queue_JoinQueueResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_queue_JoinQueueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_JoinQueueResponse_descriptor,
        new java.lang.String[] { "Success", "Position", "Waiting", "Message", });
    internal_static_queue_LeaveQueueRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_queue_LeaveQueueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_LeaveQueueRequest_descriptor,
        new java.lang.String[] { "ServiceId", "LocationId", "UserId", });
    internal_static_queue_LeaveQueueResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_queue_LeaveQueueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_LeaveQueueResponse_descriptor,
        new java.lang.String[] { "Success", "Waiting", "Message", });
    internal_static_queue_QueueStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_queue_QueueStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_QueueStatusRequest_descriptor,
        new java.lang.String[] { "ServiceId", "LocationId", "UserId", });
    internal_static_queue_QueueStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_queue_QueueStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_QueueStatusResponse_descriptor,
        new java.lang.String[] { "UserId", "Position", "Waiting", "Event", "Detail", "UpdatedAt", });
    internal_static_queue_GetPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_queue_GetPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_GetPositionRequest_descriptor,
        new java.lang.String[] { "ServiceId", "LocationId", "UserId", });
    internal_static_queue_GetPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_queue_GetPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_GetPositionResponse_descriptor,
        new java.lang.String[] { "InQueue", "Position", "Waiting", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
