// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface RequestStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.RequestStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 requestId = 1;</code>
   * @return The requestId.
   */
  long getRequestId();
}
