// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

package com.example.QueueAndUpdateService.grpc;

public interface RequestStatusUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.RequestStatusUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
