grpc.server.port=${GRPC_SERVER_PORT:9090}
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
server.port=${SERVER_PORT:8085}
server.http2.enabled=${SERVER_HTTP2_ENABLED:true}
grpc.server.security.enabled=${GRPC_SERVER_SECURITY_ENABLED:false}
logging.level.net.devh.boot.grpc=${LOGGING_LEVEL_NET_DEVH_BOOT_GRPC:DEBUG}
