spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:public_services_db}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/public_services_db}
server.port=${SERVER_PORT:8082}